"""Generate block: turn a hypothesis into a runnable test program.

A hypothesis is a claim about where two models might disagree; this block turns
it into bare-metal RISC-V that actually reaches the seam and terminates.

The part that matters is the validation gate. Generated assembly fails in ways
that are easy to mistake for results: it does not assemble, or it assembles and
never terminates, or it terminates immediately having executed nothing
interesting. A program that runs zero instructions produces a clean comparison,
and a loop that counts clean comparisons as evidence of correctness will happily
report that a broken generator found no bugs. So every program is assembled,
executed on the oracle under an instruction budget, and required to retire a
minimum number of instructions before it is allowed into the suite.

Category templates are real, working programs rather than sketches. They are the
offline baseline the model's output is measured against, so they have to clear
the same gate.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field

from . import models, trace
from .agent import Agent
from .hypothesize import Hypothesis

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROGS = os.path.join(REPO, "tests", "progs")
GENERATED = os.path.join(PROGS, "generated")

# Bodies only: render() supplies the prologue, trap setup and the tohost exit.
TEMPLATES: dict[str, tuple[str, bool]] = {
    "BYPASS_FORWARD": ("""\
  /* Dependent chain mixing 32- and 64-bit operations. The w-suffixed forms
     sign-extend their 32-bit result into a 64-bit register, so a bypass path
     that forwards the wrong width shows up as wrong upper bits. */
  li    t0, 0x7fffffff
  addw  t1, t0, t0
  add   t2, t1, t1
  slliw t3, t1, 1
  li    t4, -1
  addw  t5, t4, t4
  mul   t6, t1, t2
  subw  a0, t6, t1
  sraiw a1, a0, 3
  addw  a2, a1, a0
  add   a3, a2, a2
  sllw  a4, a3, a1
  srlw  a5, a4, 2
  addw  a6, a5, a3
  add   a7, a6, a6
""", False),

    "MEMORY_ORDERING": ("""\
  /* Store-to-load forwarding with partial overlap: a doubleword store followed
     by narrower loads at offsets inside it, then byte and halfword stores that
     partially overwrite it and are immediately re-read. */
  la    t0, scratch
  li    t1, 0x0123456789abcdef
  sd    t1, 0(t0)
  lb    t2, 0(t0)
  lbu   t3, 1(t0)
  lh    t4, 2(t0)
  lhu   t5, 4(t0)
  lw    t6, 0(t0)
  li    a0, 0xaa
  sb    a0, 3(t0)
  ld    a1, 0(t0)
  lw    a2, 0(t0)
  li    a3, 0x55aa
  sh    a3, 6(t0)
  ld    a4, 0(t0)
  lwu   a5, 4(t0)
  fence
  ld    a6, 0(t0)
  lbu   a7, 3(t0)
""", False),

    "QUEUE_POINTER": ("""\
  /* Drive the store and load queues toward capacity, then interleave, so that
     pushes and pops land in the same cycle near the wrap point. */
  la    t0, scratch
  li    t1, 0
  .rept 24
  sd    t1, 0(t0)
  addi  t1, t1, 1
  .endr
  .rept 24
  ld    t2, 0(t0)
  .endr
  .rept 16
  sd    t1, 8(t0)
  ld    t3, 8(t0)
  .endr
  li    a0, 0
  .rept 64
  addi  a0, a0, 1
  .endr
""", False),

    "EXCEPTION_PRIORITY": ("""\
  /* Take several trap kinds in sequence and capture mcause after each, so the
     cause values themselves land in the committed trace. 0xc0001073 writes a
     read-only CSR, which is a well-defined illegal instruction. */
  .word 0xc0001073
  mv    a0, s2
  ecall
  mv    a1, s2
  ebreak
  mv    a2, s2
  la    t0, scratch
  addi  t0, t0, 1
  lh    t1, 0(t0)
  mv    a3, s2
  lw    t2, 0(t0)
  mv    a4, s2
""", True),

    "ACKNOWLEDGED_GAP": ("""\
  /* No targeted stimulus: this category's seams are TODO markers, which say
     where the RTL is unfinished but not how to reach it. Exercises a broad mix
     so the program is at least a valid, terminating baseline. */
  la    t0, scratch
  li    t1, 0x1234
  sd    t1, 0(t0)
  ld    t2, 0(t0)
  addw  t3, t2, t1
  mul   t4, t3, t2
  div   t5, t4, t1
  rem   t6, t4, t1
  fence
  li    a0, 0
  .rept 32
  addi  a0, a0, 1
  .endr
""", False),
}

PROLOGUE = """\
/* Generated by chia_loop.generate -- do not edit by hand.
 * hypothesis: {hid}
 * category:   {category}
 * provenance: {provenance}
 */
#include "common.S"

  .section .text.init
  .globl _start
_start:
"""


@dataclass
class TestProgram:
    id: str
    hypothesis_id: str
    category: str
    body: str
    needs_trap: bool = False
    provenance: str = "offline-template"
    path: str = ""

    def render(self) -> str:
        head = PROLOGUE.format(hid=self.hypothesis_id, category=self.category,
                               provenance=self.provenance)
        setup = "  TRAP_SETUP\n" if self.needs_trap else ""
        return head + setup + self.body + "  TEST_PASS\n"

    def write(self, directory: str = GENERATED) -> str:
        os.makedirs(directory, exist_ok=True)
        self.path = os.path.join(directory, f"{self.id}.S")
        with open(self.path, "w") as fh:
            fh.write(self.render())
        return self.path


@dataclass
class Validation:
    """Why a program was accepted or rejected. Rejections are not failures of
    the loop; they are the gate doing its job, and the counts are worth
    reporting."""

    ok: bool = False
    assembles: bool = False
    terminates: bool = False
    events: int = 0
    reason: str = ""
    detail: str = field(default="", repr=False)

    def to_dict(self) -> dict:
        return {"ok": self.ok, "assembles": self.assembles,
                "terminates": self.terminates, "events": self.events,
                "reason": self.reason}


def validate(program: TestProgram, min_events: int = 8,
             max_insns: int = 200_000, start_pc: int = 0x80000000) -> Validation:
    """Assemble, run on the oracle, and require real work to have happened."""
    v = Validation()
    if not program.path:
        program.write()

    elf = os.path.join(REPO, "build", "progs", f"{program.id}.elf")
    build = models.build_elf(program.path, elf)
    if not build.ok:
        v.reason = "does not assemble"
        v.detail = build.output[-3000:]
        return v
    v.assembles = True

    res = models.run_spike(elf, max_insns=max_insns)
    events = trace.truncate_at_halt(trace.parse_commit_log(res.output))
    after_sync = [e for n, e in enumerate(events)
                  if any(x.pc == start_pc for x in events[:n + 1])]
    v.events = len(after_sync)

    if not res.ok:
        v.reason = f"oracle exited {res.returncode}"
        v.detail = res.output[-3000:]
        return v
    v.terminates = True

    if v.events < min_events:
        v.reason = (f"retired only {v.events} instructions after sync "
                    f"(minimum {min_events}); a program that does nothing "
                    "produces a clean comparison and proves nothing")
        return v

    v.ok = True
    v.reason = "accepted"
    return v


_PROMPT = """You are writing a bare-metal RISC-V test program to expose a \
disagreement between an out-of-order implementation (BOOM) and ISA reference \
models (Spike, Dromajo) over COMMITTED architectural state.

Hypothesis: {title}
Category: {category}
Rationale: {rationale}
Preconditions: {preconditions}
Intended stimulus: {stimulus}
Expected divergence: {expected}

Write ONLY the instruction sequence for the body of _start.

DESIGN THE TEST SO A DEFECT IS EASY TO SEE AND EASY TO CLASSIFY:
1. Localise the effect. Drive the suspect microarchitectural condition, then
   capture its result into ONE callee-saved register (s2-s11) and leave it
   there. A single wrong register value is an unambiguous divergence; a wrong
   value that flows into a branch or an address derails the whole trace and
   looks like a harness artifact instead of a bug.
2. No data-dependent control flow after the suspect value is produced. Do not
   branch on it, do not use it as a load/store address. Keep control flow
   identical on both machines so the ONLY possible divergence is the captured
   value.
3. Make the two outcomes numerically distinct. Arrange operands so the correct
   result and the buggy result differ in low bits that are obvious in a commit
   log (avoid values that alias to 0).
4. Exercise the seam repeatedly with varied operands (a short .rept or an
   unrolled sequence) to raise the chance of hitting the precondition, but keep
   the program under ~60 instructions and strictly terminating.

CONSTRAINTS:
- RV64GC, GNU as syntax. No prologue, _start label, .section, or exit code.
- Touch only the 256-byte buffer at symbol `scratch`.
- No pseudo-ops needing relaxation other than `la`. `.rept`/`.endr` allowed.
- The program MUST terminate: no unbounded loops, no jumps outside the body.
{trap_note}
Respond as JSON: {{"body": "<assembly>", "needs_trap": true|false, \
"explanation": "<one sentence naming the register that will differ>"}}
"""

TRAP_NOTE = """- A trap handler is installed for you. It records mcause into s2 \
and steps over the faulting instruction, so you may deliberately trap and then \
read s2 to place the cause into committed state.
"""


def _sanitize(body: str) -> str:
    """Strip anything the render path already supplies or that could escape it.

    A generated body that redefines _start or emits its own .section silently
    changes the program's layout, and a tohost write ends the run early.
    """
    out = []
    banned = re.compile(r"^\s*(\.section|\.globl\s+_start|_start\s*:|"
                        r"\.text|\.data|\.bss|#include)", re.I)
    for line in body.splitlines():
        if banned.match(line):
            continue
        if "tohost" in line:
            continue
        out.append(line.rstrip())
    text = "\n".join(out).strip("\n")
    return text + "\n" if text else ""


def synthesize(hypothesis: Hypothesis, agent: Agent | None = None,
               index: int = 1) -> TestProgram:
    agent = agent or Agent()
    pid = f"{hypothesis.category.lower()}_{index}"

    if not agent.online:
        body, needs_trap = TEMPLATES.get(
            hypothesis.category, TEMPLATES["ACKNOWLEDGED_GAP"])
        return TestProgram(pid, hypothesis.id, hypothesis.category, body,
                           needs_trap, "offline-template")

    prompt = _PROMPT.format(
        title=hypothesis.title, category=hypothesis.category,
        rationale=hypothesis.rationale, preconditions=hypothesis.preconditions,
        stimulus=hypothesis.stimulus_sketch,
        expected=hypothesis.expected_divergence,
        trap_note=TRAP_NOTE if hypothesis.category == "EXCEPTION_PRIORITY" else "")
    try:
        raw = agent.complete(prompt)
    except Exception:                                   # noqa: BLE001
        body, needs_trap = TEMPLATES.get(
            hypothesis.category, TEMPLATES["ACKNOWLEDGED_GAP"])
        return TestProgram(pid, hypothesis.id, hypothesis.category, body,
                           needs_trap, "offline-template (model call failed)")

    from .agent import _parse_json
    data = _parse_json(raw)
    body = _sanitize(str(data.get("body", "")))
    if not body:
        body, needs_trap = TEMPLATES.get(
            hypothesis.category, TEMPLATES["ACKNOWLEDGED_GAP"])
        return TestProgram(pid, hypothesis.id, hypothesis.category, body,
                           needs_trap, "offline-template (empty model output)")

    return TestProgram(pid, hypothesis.id, hypothesis.category, body,
                       bool(data.get("needs_trap", False)), agent.provenance)


def generate_suite(hypotheses: list[Hypothesis], agent: Agent | None = None,
                   min_events: int = 8) -> list[tuple[TestProgram, Validation]]:
    agent = agent or Agent()
    seen: dict[str, int] = {}
    out = []
    for h in hypotheses:
        seen[h.category] = seen.get(h.category, 0) + 1
        prog = synthesize(h, agent=agent, index=seen[h.category])
        prog.write()
        out.append((prog, validate(prog, min_events=min_events)))
    return out
